# Makes it so that the post URL doesn't have the date in it
permalink: /:title/

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

title: Daniel Coelho's Blog
tagline: 'Software engineering and other stuff'
description: 'Blog posts about software engineering, Unreal Engine, AI, and more. Also lists my personal projects (whenever I finish them)'
url: "https://1danielcoelho.github.io"
baseurl: "/"
github: [metadata]
logo: '/assets/images/me.jpg'

author:
  name: Daniel Coelho
  github: 1danielcoelho
  email: 1danielcoelho@gmail.com
  linkedin: daniel-coelho-103109b7
  twitter: _daniel_coelho_

twitter:
  card: summary
  username: _daniel_coelho_

social:
  name: Daniel Coelho
  links:
    - https://www.linkedin.com/in/daniel-coelho-103109b7
    - https://github.com/1danielcoelho
    - https://twitter.com/_daniel_coelho_

show_excerpts: true

exclude:
  - todo.md
  - third_party_licenses/LICENSE.Hyde.md
  - third_party_licenses/LICENSE.Poole.md
  - LICENSE

plugins:
  - jekyll-prism-plugin
  - jekyll-sitemap
  - jekyll-seo-tag
