# Makes it so that the post URL doesn't have the date in it
permalink: /:title/

# Setup
title: Daniel Coelho's blog
tagline: 'Software engineering and other stuff'
description: 'Software engineering and other stuff'
url: "https://1danielcoelho.github.io"
baseurl: "/"
github: [metadata]

author:
  name: Daniel Coelho
  github: 1danielcoelho
  email: 1danielcoelho@gmail.com
  linkedin: daniel-coelho-103109b7

show_excerpts: true

# Custom vars
version: 2.1.0

exclude:
  - todo.md
  - third_party_licenses/LICENSE.Hyde.md
  - third_party_licenses/LICENSE.Poole.md
  - LICENSE
