# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Daniel Coelho's blog
email: 1danielcoelho@gmail.com
tagline: 'A Jekyll theme'
description: 'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: ""
baseurl: "/"
github: [metadata]

author:
  name: 'Daniel Coelho'
  url: https://twitter.com/mdo

paginate: 1

# Custom vars
version: 2.1.0

exclude:
  - todo.md
